name: R Package CI/CD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, master ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Build package
        run: bash scripts/package.sh

      - name: Get package info
        run: |
          PKG_VERSION=$(grep "Version:" DESCRIPTION | cut -d' ' -f2)
          PKG_NAME=$(grep "Package:" DESCRIPTION | cut -d' ' -f2)
          echo "PKG_FILE=${PKG_NAME}_${PKG_VERSION}.tar.gz" >> $GITHUB_ENV

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: r-package
          path: ${{ env.PKG_FILE }}